name: Artifact Generation

on: release

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build h3-node
      run: yarn

    - name: Generate Artifact
      run: |
        base=`basename $PWD`
        cd -P ..
        tar -czf /tmp/h3-node-ubuntu-${{ matrix.node-version }}.tar.gz $base

    - name: Upload Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.upload_url }}
        asset_path: /tmp/h3-node-ubuntu-${{ matrix.node-version }}.tar.gz
        asset_name: h3-node-ubuntu-${{ matrix.node-version }}.tar.gz
        asset_content_type: application/gzip

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build h3-node
      run: yarn

    - name: Generate Artifact
      run: |
        zip -r h3-node-windows-${{ matrix.node-version }}.zip .

    - name: Upload Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.upload_url }}
        asset_path: h3-node-windows-${{ matrix.node-version }}.zip
        asset_name: h3-node-windows-${{ matrix.node-version }}.zip
        asset_content_type: application/zip

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build h3-node
      run: yarn

    - name: Generate Artifact
      run: |
        base=`basename $PWD`
        cd -P ..
        tar -czf /tmp/h3-node-macos-${{ matrix.node-version }}.tar.gz $base

    - name: Upload Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.upload_url }}
        asset_path: /tmp/h3-node-macos-${{ matrix.node-version }}.tar.gz
        asset_name: h3-node-macos-${{ matrix.node-version }}.tar.gz
        asset_content_type: application/gzip